-- Campus Ambassador payouts ledger: append-only table for commission earned and payouts made.
-- Two kinds: 'commission_earned' (auto-generated by trigger on order paid), 'payout_made' (manual by superadmin).

CREATE TYPE public.campus_ambassador_payout_kind AS ENUM (
  'commission_earned',
  'payout_made'
);

CREATE TABLE IF NOT EXISTS public.campus_ambassador_payouts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ambassador_id uuid NOT NULL REFERENCES public.campus_ambassadors(id) ON DELETE CASCADE,
  kind public.campus_ambassador_payout_kind NOT NULL,
  amount_minor bigint NOT NULL CHECK (amount_minor > 0),
  order_id uuid NULL REFERENCES public.orders(id) ON DELETE SET NULL,
  paid_via text NULL,
  reference_text text NULL CHECK (char_length(reference_text) <= 200),
  created_by uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Idempotency: one commission_earned per order
CREATE UNIQUE INDEX IF NOT EXISTS idx_payouts_earned_order_id
  ON public.campus_ambassador_payouts(order_id)
  WHERE kind = 'commission_earned' AND order_id IS NOT NULL;

-- Query performance: list by ambassador
CREATE INDEX IF NOT EXISTS idx_payouts_ambassador_kind_created
  ON public.campus_ambassador_payouts(ambassador_id, kind, created_at DESC);

-- RLS
ALTER TABLE public.campus_ambassador_payouts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS payouts_superadmin_all ON public.campus_ambassador_payouts;
CREATE POLICY payouts_superadmin_all ON public.campus_ambassador_payouts
  FOR ALL USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());

-- Student can only SELECT their own payouts
DROP POLICY IF EXISTS payouts_select_own ON public.campus_ambassador_payouts;
CREATE POLICY payouts_select_own ON public.campus_ambassador_payouts
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.campus_ambassadors ca
      WHERE ca.id = campus_ambassador_payouts.ambassador_id
        AND ca.user_id = auth.uid()
    )
  );
